### PR TITLE
Remove EntraApplicationCheck class

### PR DESCRIPTION
**Pull request by Saurabh7019**
## 🎯 Aim

> The EntraApplicationCheck was previously used during the transition period to verify usage of the PnP Management Shell app. Since the app has been removed and the check is no longer needed, the EntraApplicationCheck class and its reference in CommandPanel have been removed.

## ✅ What was done

- [X] Removed EntraApplicationCheck class and its reference in CommandPanel.

## 🔗 Related issue

Closes: #330

### CODE REVIEW

**Comment by Adam-it** [comment]
Thank you for opening a PR. I will review it ASAP. 
You Rock 🤩

**Comment by Adam-it** [comment]
@Saurabh7019 I just checked and you are the most active contributor to this repository if I check stats from last 6 months. 
Since we are always searching for folks that could present something on one of the PnP Community Calls I was wondering if maybe you would like to present SPFx Toolkit on one of the calls? 
It could be about how you use this tool, or could be used? or how you extend this tool and what are your experience with it and present the functionalities you worked on? Or just a genera intro about the tool and how would you like it to evolve in future or what problems you have in your day to day life this tool is NOT helpful and you would like this to change? Or maybe the scope of the tool is too small and you would like to expand it to something bigger?
Anything works, any feed is wanted and any experience, either how you use it or what you build to this tool, may be shared with the community. The aim of PnP is to learn from each other. Sharing is Caring 🙂

**Comment by Saurabh7019** [comment]
Thank you for the opportunity, @Adam-it. I would be happy to talk about the SPFx Toolkit in one of the PnP community call. I have watched all your community videos on the toolkit, where you have covered most of its features in detail. Given that, I think sharing how I use it in my work might feel a bit repetitive for some. But, I would be glad to present my experience with the tool by combining how I use it with one or two features that haven't yet been covered in your videos, if that sounds good?

**Comment by Adam-it** [comment]
> Thank you for the opportunity, @Adam-it. I would be happy to talk about the SPFx Toolkit in one of the PnP community call. I have watched all your community videos on the toolkit, where you have covered most of its features in detail. Given that, I think sharing how I use it in my work might feel a bit repetitive for some. But, I would be glad to present my experience with the tool by combining how I use it with one or two features that haven't yet been covered in your videos, if that sounds good?

Sounds perfect, I would love to see that myself. 
May I kindly ask you to fill out the form
https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR8ke1rGfE-VNsUHrnMWCrL5UNjhIVEc4VERQUDNYOTM4MDdKN1ZLWFVBMSQlQCN0PWcu

So that we may setup a slot for your demo

**Comment by Saurabh7019** [comment]
I will fill out the form right away. 
Since it's my first time, and much of it will be inspired by your presentations, can I please give your name for a potential co-presenter?

**Comment by Adam-it** [comment]
> I will fill out the form right away. Since it's my first time, and much of it will be inspired by your presentations, can I please give your name for a potential co-presenter?

Totally!!!!

**Review by Adam-it — APPROVED** [review]
Perfect 🤩 
@Saurabh7019 Awesome work 👏👏👏👏

**Comment by Adam-it** [comment]
> I will fill out the form right away. Since it's my first time, and much of it will be inspired by your presentations, can I please give your name for a potential co-presenter?

contact me directly if you wanna recheck how to share the demo, what you want me to cover 👍.
This will be merged shortly. Thank you for another awesome contribution 👍 You Rock 🤩

**Pull request merged**
