### PR TITLE
Added more settings

### PR DESCRIPTION
**Pull request by GuidoZam**
## 🎯 Aim

This PR implements the required settings of issue [#200](https://github.com/pnp/vscode-viva/issues/200).

## 📷 Result

image

## ✅ What was done

Added two settings for the extension:
- showServiceIncidentList
- showTenantWideExtensions

Updated the `TerminalCommandExecuter` extracting the `getExtensionSettings` method and creating a dedicated util file.

Updated the `CommandPanel` to keep into account the new settings when loading and showing data.

- [] not done
- [X] done

## 🔗 Related issue

Closes: #200

### CODE REVIEW

**Comment by Adam-it** [comment]
@GuidoZam thanks for this PR! You Rock 🤩.
Before we proceed may I kindly ask you to: 
- rebase your branch against latest dev. It seems we already have some conflicts on this PR and most probably the dev branch you started with was outdated.
- leave a comment in the related issue się that I may assign it to you and in future please let's start by getting assigned to the issue first and then opening the PR with the change. That way we will ensure only a single person is working on some improvement.

**Comment by GuidoZam** [comment]
Sorry, I thought to have the latest version, I'll check it asap.

**Comment by GuidoZam** [comment]
I've resolved the conflicts, you should be able to merge now.

**Review by Adam-it — APPROVED** [review]
Awesome 👏👏👏
I only have a single comment I will resolve when merging 👍

**Pull request merged**
